Combining the two files from Simran and Zach

In [1]:
import pandas as pd

In [6]:
Movie_budget_db = pd.read_csv('Final_Data/Movie_budget.csv')
Scrapped_budget_db = pd.read_csv('zippedData/movieMoney.csv')

Movie_budget_db.drop(columns ='_merge', inplace=True)
print('Movie_budget_db''\n', Movie_budget_db.head(),'\n', Movie_budget_db.shape,'\n')

Scrapped_budget_db['Production_Budget'].replace('[\$,]', '', regex=True, inplace=True)
Scrapped_budget_db['Production_Budget'] = Scrapped_budget_db['Production_Budget'].astype('float')
Scrapped_budget_db['Gross_Domestic'].replace('[\$,]', '', regex=True, inplace=True)
Scrapped_budget_db['Gross_Domestic'] = Scrapped_budget_db['Gross_Domestic'].astype('float')
Scrapped_budget_db['Gross_Worldwide'].replace('[\$,]', '', regex=True, inplace=True)
Scrapped_budget_db['Gross_Worldwide'] = Scrapped_budget_db['Gross_Worldwide'].astype('float')

print('Scrapped_budget_db''\n', Scrapped_budget_db.head(),'\n', Scrapped_budget_db.shape,'\n')

Movie_budget_db
   release_date  production_budget  worldwide_gross studio  foreign_gross  \
0   1994-09-23         25000000.0     2.830709e+07    NaN        65623.0
1   2008-07-18        185000000.0     1.001996e+09    NaN    468275260.0
2   2010-07-16        160000000.0     8.355246e+08     WB    535700000.0
3   1999-10-15         65000000.0     1.008517e+08    NaN     63821603.0
4   1994-10-14          8000000.0     2.129288e+08    NaN    105000000.0

     year budget_merge  domestic_gross               Movie_title     tconst  \
0  1994.0    left_only      28241469.0  The Shawshank Redemption  tt0111161
1  2008.0    left_only     533720947.0           The Dark Knight  tt0468569
2  2010.0         both     292576195.0                 Inception  tt1375666
3  1999.0    left_only      37030102.0                Fight Club  tt0137523
4  1994.0    left_only     107928762.0              Pulp Fiction  tt0110912

  runtimeMinutes  averageRating   numVotes  region  language
0            142            9.3  2259481.0    60.0      60.0
1            152            9.0  2225006.0    59.0      59.0
2            148            8.8  1982266.0    52.0      52.0
3            139            8.8  1794853.0     NaN       NaN
4            154            8.9  1767823.0    51.0      51.0
 (7921, 15)

Scrapped_budget_db
    Unnamed: 0  Release_Date                                   Movie_Name  \
0           0  Apr 23, 2019                            Avengers: Endgame
1           1  May 20, 2011  Pirates of the Caribbean: On Stranger Tides
2           2  Apr 22, 2015                      Avengers: Age of Ultron
3           3  Dec 16, 2015         Star Wars Ep. VII: The Force Awakens
4           4  Apr 25, 2018                       Avengers: Infinity War

   Production_Budget  Gross_Domestic  Gross_Worldwide
0        400000000.0     858373000.0     2.797801e+09
1        379000000.0     241063875.0     1.045664e+09
2        365000000.0     459005868.0     1.396099e+09
3        306000000.0     936662225.0     2.065478e+09
4        300000000.0     678815482.0     2.048360e+09
 (5943, 6)

In [10]:

# Final_Movie_Budget = Movie_budget_db.merge(Scrapped_budget_db, how='outer', left_on='Movie_title',
#                                           right_on='Movie_Name', indicator=True)
# print('Final_Movie_Budget''\n', Final_Movie_Budget.head(),'\n', Final_Movie_Budget.shape,'\n')
Final_Movie_Budget[Final_Movie_Budget['_merge']=='left_only']

,release_date,production_budget,worldwide_gross,studio,foreign_gross,year,budget_merge,domestic_gross,Movie_title,tconst,...,numVotes,region,language,Unnamed: 0,Release_Date,Movie_Name,Production_Budget,Gross_Domestic,Gross_Worldwide,_merge
2,2010-07-16,160000000.0,835524642.0,WB,535700000.0,2010.0,both,292576195.0,Inception,tt1375666,...,1982266.0,52.0,52.0,NaN,NaN,NaN,NaN,NaN,NaN,left_only
11,2014-11-05,165000000.0,666379375.0,Par.,489400000.0,2014.0,both,188017894.0,Interstellar,tt0816692,...,1431303.0,46.0,46.0,NaN,NaN,NaN,NaN,NaN,NaN,left_only
15,2005-06-15,150000000.0,359142722.0,NaN,153798948.0,2005.0,left_only,205343774.0,Batman Begins,tt0372784,...,1269282.0,51.0,51.0,NaN,NaN,NaN,NaN,NaN,NaN,left_only
31,2014-08-01,170000000.0,770867516.0,BV,440200000.0,2014.0,both,333172112.0,Guardians of the Galaxy,tt2015381,...,1017602.0,51.0,51.0,NaN,NaN,NaN,NaN,NaN,NaN,left_only
36,2003-07-09,140000000.0,634954103.0,NaN,329542879.0,2003.0,left_only,305411224.0,Pirates of the Caribbean: The Curse of the Bla...,tt0325980,...,997410.0,47.0,47.0,NaN,NaN,NaN,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8083,NaN,NaN,NaN,CLS,NaN,2018.0,right_only,NaN,"Lou Andreas-Salomé, the Audacity to be Free",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
8084,NaN,NaN,NaN,PDF,NaN,2018.0,right_only,NaN,Hannah (2018),NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
8085,NaN,NaN,NaN,CARUSEL,NaN,2018.0,right_only,NaN,Furious (Legend of Kolovrat),NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
8086,NaN,NaN,NaN,FM,NaN,2018.0,right_only,NaN,Edward II (2018 re-release),NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
8087,NaN,NaN,NaN,Sony,NaN,2018.0,right_only,NaN,El Pacto,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [29]:
Final_Movie_Budget.loc[Final_Movie_Budget['_merge']=='left_only', 'Production_Budget'] = Final_Movie_Budget[Final_Movie_Budget['_merge']=='left_only']['production_budget']
Final_Movie_Budget.loc[Final_Movie_Budget['_merge']=='left_only', 'Gross_Worldwide'] = Final_Movie_Budget[Final_Movie_Budget['_merge']=='left_only']['worldwide_gross']
Final_Movie_Budget.loc[Final_Movie_Budget['_merge']=='left_only', 'Gross_Domestic'] = Final_Movie_Budget[Final_Movie_Budget['_merge']=='left_only']['domestic_gross']
Final_Movie_Budget.loc[Final_Movie_Budget['_merge']=='left_only', 'Gross_Foreign_Only'] = Final_Movie_Budget[Final_Movie_Budget['_merge']=='left_only']['foreign_gross']
Final_Movie_Budget.loc[Final_Movie_Budget['_merge']=='left_only', 'Release_Date'] = Final_Movie_Budget[Final_Movie_Budget['_merge']=='left_only']['release_date']
Final_Movie_Budget.loc[Final_Movie_Budget['_merge']!='left_only', 'Gross_Foreign_Only'] = (Final_Movie_Budget[Final_Movie_Budget['_merge']!='left_only']['Gross_Worldwide']) - (Final_Movie_Budget[Final_Movie_Budget['_merge']!='left_only']['Gross_Domestic'])

In [33]:
drop_list = ['production_budget', 'worldwide_gross', 'release_date', 'foreign_gross', 'budget_merge', 'domestic_gross', 'Unnamed: 0']
Final_Movie_Budget.drop(columns= drop_list, inplace=True)
Final_Movie_Budget.loc[Final_Movie_Budget['_merge']=='both']

,studio,year,Movie_title,tconst,runtimeMinutes,averageRating,numVotes,region,language,Release_Date,Movie_Name,Production_Budget,Gross_Domestic,Gross_Worldwide,_merge,Gross_Foreign_Only
0,NaN,1994.0,The Shawshank Redemption,tt0111161,142,9.3,2259481.0,60.0,60.0,"Sep 23, 1994",The Shawshank Redemption,25000000.0,28241469.0,2.841706e+07,both,175591.0
1,NaN,2008.0,The Dark Knight,tt0468569,152,9.0,2225006.0,59.0,59.0,"Jul 11, 2008",The Dark Knight,185000000.0,533720947.0,1.000743e+09,both,467021804.0
3,NaN,1999.0,Fight Club,tt0137523,139,8.8,1794853.0,NaN,NaN,"Oct 15, 1999",Fight Club,65000000.0,37030102.0,1.008345e+08,both,63804388.0
4,NaN,1994.0,Pulp Fiction,tt0110912,154,8.9,1767823.0,51.0,51.0,"Sep 10, 1994",Pulp Fiction,8000000.0,107928762.0,2.129119e+08,both,104983148.0
5,NaN,1994.0,Forrest Gump,tt0109830,142,8.8,1741545.0,41.0,41.0,"Jul 6, 1994",Forrest Gump,55000000.0,330151138.0,6.798383e+08,both,349687122.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7425,NaN,2015.0,Family Motocross,NaN,NaN,NaN,NaN,NaN,NaN,"May 19, 2015",Family Motocross,10000.0,0.0,0.000000e+00,both,0.0
7426,NaN,2004.0,The Mongol King,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,The Mongol King,7000.0,900.0,9.000000e+02,both,0.0
7427,NaN,2005.0,My Date With Drew,NaN,NaN,NaN,NaN,NaN,NaN,"Aug 5, 2005",My Date With Drew,1100.0,181041.0,1.810410e+05,both,0.0
7829,GK,2015.0,Kahlil Gibran's The Prophet,NaN,NaN,NaN,NaN,NaN,NaN,"Aug 7, 2015",Kahlil Gibran's The Prophet,12000000.0,340536.0,1.080362e+06,both,739826.0
7893,FIP,2016.0,El Clan,NaN,NaN,NaN,NaN,NaN,NaN,"Aug 13, 2015",El Clan,5500000.0,201227.0,2.212510e+07,both,21923875.0

In [24]:
Final_Movie_Budget.loc[(Final_Movie_Budget['_merge']=='left_only') & (Final_Movie_Budget['foreign_gross'].isna()), 'drop_rows'] = 'delete'
Final_Movie_Budget.drop(Final_Movie_Budget[Final_Movie_Budget['drop_rows']=='delete'].index, inplace=True)

In [25]:
Final_Movie_Budget.drop(columns= 'drop_rows', inplace=True)

In [34]:
Final_Movie_Budget.to_csv('Final_Data/Final_Movie_Budget.csv')